app:
  name: customers
  namespace: customers-{{ code_red_breach_challenge_gitea_customize_lab_username }}
  cluster: .{{ code_red_breach_challenge_gitea_customize_apps_subdomain }}
  challenge_password: "{{ code_red_breach_challenge_gitea_customize_lab_challenge_password }}"

git:
  branch: master
  repo: https://{{ code_red_breach_challenge_gitea_customize_gitea_endpoint }}/gitea/{{ code_red_breach_challenge_gitea_customize_lab_username }}-pipeline-gitops.git
  org: development
  name: pipeline-gitops
  host: {{ code_red_breach_challenge_gitea_customize_gitea_endpoint }}
  token: ''
  webhookSecret: ''
  verify_commits: disabled

lab:
  username: {{ code_red_breach_challenge_gitea_customize_lab_username }}

image:
  registry: Quay
  organization: quayadmin
  host: {{ code_red_breach_challenge_gitea_customize_quay_server }}
  name: customers-{{ code_red_breach_challenge_gitea_customize_lab_username }}
  tag: v1
